FROM node:20-alpine
WORKDIR /app

COPY package.json .yarnrc.yml yarn.lock ./
COPY apps/web/package.json ./apps/web/
COPY packages/types/package.json ./packages/types/

RUN corepack enable && yarn install

COPY packages/types ./packages/types
COPY apps/web ./apps/web

EXPOSE 3000
CMD ["yarn", "workspace", "@bulk/web", "dev"]
