services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./packages/db/src:/app/packages/db/src
      - ./packages/types/src:/app/packages/types/src

  worker:
    build:
      context: .
      dockerfile: packages/worker/Dockerfile.dev
    volumes:
      - ./packages/worker/src:/app/packages/worker/src
      - ./packages/db/src:/app/packages/db/src
      - ./packages/types/src:/app/packages/types/src

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
      args:
        NEXT_PUBLIC_API_URL: http://localhost:4000
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - ./apps/web/app:/app/apps/web/app
      - ./apps/web/public:/app/apps/web/public
      - ./packages/types/src:/app/packages/types/src
    ports:
      - "3000:3000"
    command: ["yarn", "workspace", "@bulk/web", "dev"]
